# Gunakan Node.js versi LTS sebagai base image
FROM node:18-alpine AS base

# Set working directory di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json untuk menginstal dependensi
COPY package.json package-lock.json ./

# Install dependensi menggunakan npm
RUN npm install

# Salin seluruh kode proyek ke working directory
COPY . .

# Stage untuk build aplikasi Next.js dalam mode produksi
FROM base AS builder

# Set variabel lingkungan untuk build

# Build aplikasi Next.js
RUN npm run build

# Stage untuk menjalankan aplikasi
FROM node:18-alpine AS runner

# Set working directory
WORKDIR /app

# Salin hasil build dan dependensi yang diperlukan dari stage builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Set variabel lingkungan untuk runtime
ENV PORT=3000

# Ekspos port yang digunakan aplikasi
EXPOSE 3000

# Jalankan aplikasi Next.js
CMD ["npm", "start"]